# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/tqc.yml#L206
seed: 42
n_timesteps: !!float 1e6
policy: 'MultiInputPolicy'
buffer_size: 1000000
batch_size: 256
ent_coef: 'auto'
gamma: 0.95
learning_rate: 0.001
replay_buffer_class: HerReplayBuffer
replay_buffer_kwargs: "dict(
    goal_selection_strategy='future',
    n_sampled_goal=4
)"
policy_kwargs: "dict(net_arch=[64, 64], n_critics=1)"
device: "cuda:0"
